# Smoke test sulla creazione del modello

In [1]:
from src import model

/Users/hanus/Documents/GitHub/company_sentiment/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [9]:
trained_model, training_metrics = model.train_model(
    dataset_name="train.csv",
    new_version_name= "smoke_v1",
    sample_size=10000
)

training_metrics

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 91318.79it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-roberta-base-sentiment-latest
Key                         | Status     |  |
----------------------------+------------+--+-
roberta.pooler.dense.bias   | UNEXPECTED |  |
roberta.pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
/Users/hanus/Documents/GitHub/company_sentiment/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

/Users/hanus/Documents/GitHub/company_sentiment/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.06it/s]

modello salvato correttamente

{'before training': {'before_training_loss': 0.7046950459480286,
  'before_training_accuracy': 0.7015,
  'before_training_precision': 0.7086379147063454,
  'before_training_recall': 0.7242968138167588,
  'before_training_f1': 0.700168483396181},
 'after training': {'after_training_loss': 0.5032265186309814,
  'after_training_accuracy': 0.8065,
  'after_training_precision': 0.8110973518350554,
  'after_training_recall': 0.8081855942978361,
  'after_training_f1': 0.80953820996118}}